# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('basenews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myFirstApp.BaseNews')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('myFirstApp.basenews',),
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('basenews_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myFirstApp.BaseNews')),
                ('publish_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('myFirstApp.basenews',),
        ),
    ]
