# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('es', 'Espanol (Espana)'), ('en', 'English'), ('es-es', 'Espanol (Espana)'), ('es_ES', 'Espanol (Espana)')], max_length=100, null=True, verbose_name='Preferred Language'),
        ),
    ]
