# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161107_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('es', 'Espanol (Espana)'), ('en', 'English')], max_length=100, null=True, verbose_name='Preferred Language'),
        ),
    ]
